INSERT INTO bpCurrency (CurrencyCode, CurrencyName, CurrencySymbol)
  VALUES
  ('EUR', 'Euro', N'€'),
    ('ALL', 'Albanian lek', N'L'),
    ('BYN', 'New Belarusian ruble', N'Br'),
    ('BAM', 'Bosnia and Herzegovina convertible mark', N'null'),
    ('BGN', 'Bulgarian lev', N'лв'),
    ('HRK', 'Croatian kuna', N'kn'),
    ('CZK', 'Czech koruna', N'Kč'),
    ('DKK', 'Danish krone', N'kr'),
    ('GIP', 'Gibraltar pound', N'£'),
    ('GBP', 'British pound', N'£'),
    ('HUF', 'Hungarian forint', N'Ft'),
    ('ISK', 'Icelandic króna', N'kr'),
    ('CHF', 'Swiss franc', N'Fr'),
    ('MKD', 'Macedonian denar', N'ден'),
    ('MDL', 'Moldovan leu', N'L'),
    ('NOK', 'Norwegian krone', N'kr'),
    ('PLN', 'Polish złoty', N'zł'),
    ('RON', 'Romanian leu', N'lei'),
    ('RUB', 'Russian ruble', N'₽'),
    ('RSD', 'Serbian dinar', N'дин.'),
    ('SEK', 'Swedish krona', N'kr'),
    ('UAH', 'Ukrainian hryvnia', N'₴'),
    ('CAD', 'Canadian dollar', N'$'),
    ('MXN', 'Mexican peso', N'$'),
    ('USD', 'United States dollar', N'$')